"""delete test, add avatar

Revision ID: 0b157c69fad8
Revises: 1f4bfbb9a7b4
Create Date: 2021-09-06 07:01:19.985570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b157c69fad8'
down_revision = '1f4bfbb9a7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('test_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_column', sa.VARCHAR(length=240), nullable=True))

    # ### end Alembic commands ###
