"""filename in post

Revision ID: 5ed7370c1061
Revises: a45519920521
Create Date: 2021-09-03 09:34:08.972206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed7370c1061'
down_revision = 'a45519920521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=240), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('filename')


    # ### end Alembic commands ###
